imdb:
  dataset: "imdb"
  epoches: 500
  batch_size: 512
  eva_interval: 10
  eva_epoches: 200
  num_layer: 3
  num_heads: 8
  num_out_heads: 1
  num_hidden: 512
  lr: 0.0001
  mask_rate: 0.3
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  mp2vec_feat: False

heco_acm:
  dataset: "heco_acm"
  epoches: 500
  batch_size: 8192
  eva_interval: 10
  eva_epoches: 200
  num_layer: 2
  num_heads: 8
  num_out_heads: 1
  num_hidden: 1024
  lr: 0.0008
  mask_rate: 0.5
  dynamic_mask_rate: 0.4,0.002,0.8
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  degree_recons: False
  all_feat_recons: True
  all_edge_recons: True
  all_degree_recons: False
  mp2vec_feat: False
  accumu_grad: True

heco_dblp:
  dataset: "heco_dblp"
  epoches: 500
  batch_size: 2048
  eva_interval: 10
  eva_epoches: 200
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 512
  lr: 0.0008
  mask_rate: 0.5
  dynamic_mask_rate: 0.4,0.002,0.8
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  degree_recons: False
  all_feat_recons: True
  all_edge_recons: True
  all_degree_recons: False
  mp2vec_feat: False
  accumu_grad: True


heco_aminer:
  dataset: "heco_aminer"
  epoches: 500
  batch_size: 512
  eva_interval: 10
  eva_epoches: 200
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 512
  lr: 0.0008
  mask_rate: 0.4
  dynamic_mask_rate: 0.4,0.002,0.8
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  mp2vec_feat: False
  accumu_grad: False


heco_freebase:
  dataset: "heco_freebase"
  epoches: 500
  batch_size: 512
  eva_interval: 10
  eva_epoches: 200
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 512
  lr: 0.001
  mask_rate: 0.5
  dynamic_mask_rate: 0.4,0.01,0.8
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  degree_recons: False
  all_feat_recons: True
  all_edge_recons: True
  all_degree_recons: False
  mp2vec_feat: False
  accumu_grad: False

PubMed:
  dataset: "PubMed"
  epoches: 500
  batch_size: 512
  eva_interval: 10
  eva_epoches: 200
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 512
  lr: 0.0008
  mask_rate: 0.5
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  mp2vec_feat: False
  accumu_grad: True
Yelp:
  dataset: "Yelp"
  epoches: 500
  batch_size: 1024
  eva_interval: 10
  eva_epoches: 50
  num_layer: 3
  num_heads: 8
  num_out_heads: 1
  num_hidden: 128
  lr: 0.001
  mask_rate: 0.5
  dropout: 0.4
  encoder: "SRN"
  decoder: "SRN"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  mp2vec_feat: True

Freebase:
  dataset: "Freebase"
  epoches: 500
  batch_size: 512
  eva_interval: 10
  eva_epoches: 50
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 256
  lr: 0.001
  mask_rate: 0.5
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  degree_recons: False
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  all_degree_recons: Falseß
  mp2vec_feat: False
  use_feat: "meta2vec"
  accumu_grad: True


DBLP2:
  dataset: "DBLP2"
  epoches: 500
  batch_size: 1024
  eva_interval: 10
  eva_epoches: 100
  num_layer: 1
  num_heads: 8
  num_out_heads: 1
  num_hidden: 256
  lr: 0.001
  mask_rate: 0.5
  dropout: 0.4
  encoder: "HGraphSAGE"
  decoder: "HGraphSAGE"
  weight_decay: 0.0001
  eva_lr: 0.01
  eva_wd: 0.0001
  gamma: 3
  devices: 0
  scheduler: True
  edge_recons: True
  feat_recons: True
  all_feat_recons: True
  all_edge_recons: True
  mp2vec_feat: False